<?php

/**
 * @file
 * Contains filename_transliteration.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_ENTITY_TYPE_field_values_init().
 */
function filename_transliteration_file_field_values_init(EntityInterface $entity) {
  $filename_postprocessor = Drupal::service('filename_transliteration.postprocessor');
  $filename = $entity->getFilename();
  $filename = $filename_postprocessor->process($filename);
  $entity->setFilename($filename);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function filename_transliteration_file_presave(EntityInterface $entity) {
  $filename_postprocessor = Drupal::service('filename_transliteration.postprocessor');
  $new_filename = $filename_postprocessor->process($entity->getFilename());
  $file_system = \Drupal::service('file_system');
  if ($new_filename != $file_system->basename($entity->getFileUri())) {
    $uri = $entity->getFileUri();
    $directory = $file_system->dirname($uri);
    $uri = $directory . '/' . $new_filename;
    if ($new_uri = $file_system->move($entity->getFileUri(), $uri, FileSystemInterface::EXISTS_RENAME)) {
      $entity->set('uri', $new_uri);
      $entity->set('filename', $file_system->basename($new_uri));
    }
  }
}
